### ISSUE TITLE
Unknown receiver 'ZDKConfig'; did you mean 'ZDKCoding'?

### ISSUE THREAD

**Issue by ravirupareliya** [synapsestudios/react-native-zendesk-support#25]
It is working fine with android but when i am trying to run it in iOS it is showing build error in xcode.

![Screenshot 2019-04-05 at 11 21 10 AM](https://user-images.githubusercontent.com/17959204/55606045-efb67800-5794-11e9-9a8a-5c262d4864af.png)

**Comment by caseyt** [comment]
Trying manually linking the iOS library. You can find the instructions in the README here: https://github.com/synapsestudios/react-native-zendesk-support#manually-linking-ios

Particularly, make sure you have "Header Search Paths" set up correctly, without that configured I am seeing the same error you are reporting.

**Comment by Fawxy** [comment]
Also having this issue, header search paths are set up correctly and it all appears to be linked 🤔

**Comment by YogeshYo** [comment]
I am also stuck with the same error where I checked header as well.

**Comment by YogeshYo** [comment]
@caseyt can you please look into this.. I created another wrapper to deal with this but the same issue
https://www.npmjs.com/package/react-native-zendesk-sdk

--------------------------
[Only for iOS] I am able to call testMethod (removing initialize method) but unable to compile says "Unknown receiver 'ZDKConfig'; did you mean 'ZDKCoding'?"
I am sure once I am able to call initialize i.e
RNZendeskSdk.initialize(config) things will get sorted

**Comment by YogeshYo** [comment]
@caseyt, [with Manually Linking (iOS)] still getting this error while compiling  & cross checking header path. am I missing anything?

**Comment by ryanlkuhn** [comment]
- [ ] **Test suite has been run to completion and all tests are green**

### Device testing
   Unless otherwise specified, each checklist item is to be completed once for each device listed below.
   - [ ] iOS - latest iPhone available

### SSO
- [ ] Dev iPhone 5 <details><summary>View Device Checklist</summary>

   - [ ] Attempt to log in with the test.student@suitable.co account
   - [ ] Verify that the "Suitable Ready" program is available and click the "Sign in" button for that program
   - [ ] Verify that you are redirected to sign in with Google
   - [ ] Enter the test.student@suitable.co email and google account password
   - [ ] Verify that you are returned to the app and are now signed in
</details>

### Student
#### Login / Account settings
- [ ] Enter the username for student 1 from the QA import file
- [ ] Retrieve the temporary password from internal@suitable.co inbox and log in to the mobile app

#### Header 
- [ ] Verify that the program appears as expected
- [ ] Verify that the program profile image appears as expected
- [ ] Select program name and verify that switch program modal appears as expected
- [ ] Select drop down and switch from Pitt OCC to Suitable Ready program
- [ ] Click switch button and verify that the program and current view data has changed
- [ ] Verify school image appears as expected
- [ ] Select the sign out button
- [ ] Click ok
- [ ] Verify that user is no longer signed in 
- [ ] Switch program to Suitable Ready for remainder of checklist

#### Achievements
- [ ] View **QA MM-DD-YY Featured badge** and verify that the progress bar is accurate
- [ ] Verify the link in the description of **QA MM-DD-YY Featured badge** opens the devices default browser and navigates to [suitable.co](https://www.suitable.co/) 
- [ ] View **QA MM-DD-YY Milestone badge** and verify that the progress bar is accurate
- [ ] Verify the link in the description of **QA MM-DD-YY Milestone badge** opens the devices default browser and navigates to [suitable.co](https://www.suitable.co/) 

#### Completing tasks
- [ ] Navigate to activities view
- [ ] Expand honor activity title **QA MM-DD-YY honor** and verify that the link opens the devices default browser and navigates to [suitable.co](https://www.suitable.co/)
- [ ] Complete honor activity titled **QA MM-DD-YY honor**
- [ ] Verify that a popup appears awarding points
- [ ] Verify that a popup appears showing completion of the **QA MM-DD-YY Featured badge**
- [ ] Un-complete honor activity titled **QA MM-DD-YY honor**
- [ ] Verify a popup appears warning that points will be revoked
- [ ] Verify a popup appears with a notification that the un-complete action failed
- [ ] Verify the **QA MM-DD-YY honor** is shown as completed 
- [ ] Click completed tab and verify activities exist in list
- [ ] Click upcoming tab and verify events are in list
- [ ] Click categories, select cancel and verify return to activities view with no changes
- [ ] Click categories and select 'All'

#### Achievements (cont.)
- [ ] Verify that completed badges appear adjacent to users profile image/name
- [ ] Verify that the users total level and points are displayed as expected

#### CheckIn
- [ ] Dev iPhone 5 <details><summary>View Device Checklist</summary>

  - [ ] Uninstall the Suitable app
  - [ ] Reinstall the Suitable app and log in
  - [ ] Navigate the CheckIn screen 
  - [ ] Verify that **Can we access your camera?** popup appears
  - [ ] Deny the permissions request 
  - [ ] Verify that the camera is not active and that the **Grant Access** button is visible on the screen
  - [ ] Close the app fully and navigate back to the CheckIn screen 
  - [ ] Verify that **Can we access your camera?** popup appears again
  - [ ] Accept the permissions fully and ensure proper functionality such as a camera view is displayed
  - [ ] Close the app fully and go into the permission settings for the device and revoke permissions
  - [ ] Navigate back to the CheckIn screen and verify that **Can we access your camera?** popup appears again
  - [ ] Deny the permissions request
  - [ ] Click the **Grant Access** button
  - [ ] Confirm permissions and verify that a second popup appears
  - [ ] Click the **Open Settings** option and give permissions for the Suitable App to use the camera
  - [ ] Return to the app and verify that the camera view is displayed
  - [ ] Open app in device and navigate to QR scanner view
  - [ ] Scan QR code and verify event completion
</details>


#### Notifications
- [ ] Download the [QA notifications import file](https://drive.google.com/drive/folders/1YmtmisldDJSDCAYyMEhaMrPHF43rP-07)
- [ ] Copy the Email addresses from the **roster import file** into the **notifications import file**
##### Permissions
- [ ] Dev iPhone 5 <details><summary>View Device Checklist</summary>
   
  - [ ] Navigate to the Notifications screen
  - [ ] Verify that the **Can we send you notifications..** popup appears
  - [ ] Deny the permissions request
  - [ ] Verify that the **Turn On App Notifications** and **dismiss** buttons are visible
  - [ ] Click **dismiss** and verify both buttons are no longer shown
  - [ ] Close the app fully and navigate back to the Notifications screen
  - [ ] Verify that the **Turn On App Notifications** and **dismiss** buttons are visible
  - [ ] Click **Turn On App Notifications** and Accept the permissions fully
  - [ ] Close the app fully and go into the permission settings for the device and revoke permissions
  - [ ] Navigate back to the Notifications screen and verify that the **Turn On App Notifications** and **dismiss** buttons are visible
  - [ ] Click **Turn On App Notifications** button, confirm permissions and verify that a second popup appears
  - [ ] Click the **Open Settings** option and give permissions for notifications
</details>

##### Receiving Notifications
##### From the ** Push Notification Create Form ** ( Web App )
- [ ] Send a news and nudges push notification
   - [ ] Set title to be **News and nudges!**
   - [ ] Set description to **Check this nudge out!**
   - [ ] Upload the **notifications import file** edited in the roster step
   - [ ] Lock all test devices
   - [ ] Click **Send it!** and verify the **Notification Success** message is displayed
   - [ ] Verify that the device rings/vibrates and the notification is displayed in its message center. Android devices should show a white shield notification icon at the top of the screen.
      - [ ] Dev iPhone 5
- [ ] Send a linked announcement push notification
   - [ ] Set title to be **Look at this cool website**
   - [ ] Set link to **https://www.suitable.co**
   - [ ] Upload the **notifications import file** edited in the roster step
   - [ ] Unlock and close the Suitable app on all test devices
   - [ ] Click **Send it!** and verify the **Notification Success** message is displayed
   - [ ] Verify that the Suitable app icon has a notification badge set to 1 and that a notification is received in the message center. Android devices should show a white shield notification icon at the top of the screen.
      - [ ] Dev iPhone 5
   - [ ] Verify that touching the notification opens the phones browser to **https://www.suitable.co**
- [ ] Send an achievement recommendation push notification
   - [ ] Set target achievement to **QA MM-DD-YY Featured badge**
   - [ ] Set recommended activities to **event 1 import**, **event 2 import**
   - [ ] Upload the **notifications import file** edited in the roster step
   - [ ] Unlock and run the Suitable app in the background on all test devices
   - [ ] Click **Send it!** and verify the **Notification Success** message is displayed
   - [ ] Verify that the Suitable app icon has a notification badge set to 1 and that a notification is received in the message center. Android devices should show a white shield notification icon at the top of the screen.
      - [ ] Dev iPhone 5
   - [ ] Verify that touching the notification opens Activities screen and that both **event 1 import** and **event 2 import** are showing
   - [ ] Dismiss the Recommended Activities filter below the tab bar and verify that the Activities screen returns to the default list.
- [ ] Send a container recommendation push notification
   - [ ] Set target activity to **container 1**
   - [ ] Set recommended activities to **honor activity**
   - [ ] Upload the **notifications import file** edited in the roster step
   - [ ] Unlock and run the Suitable app in the foreground on all test devices
   - [ ] Click **Send it!** and verify the **Notification Success** message is displayed
   - [ ] Verify that device rings/vibrates and the app's internal notification tab view has a badge of 1. Android devices should show a white shield notification icon at the top of the screen.
      - [ ] Dev iPhone 5
   - [ ] Verify that touching the notification opens Activities screen and that both **container 1** container is showing
   - [ ] Dismiss the Recommended Activities filter below the tab bar and verify that the Activities screen returns to the default list.


#### Leaderboard
- [ ] Verify each student card is displayed correctly
   - [ ] Rank
   - [ ] Scorecard Image
   - [ ] Last Name
   - [ ] Student Class
   - [ ] Total Points
- [ ] Click on **Go To Global Leaderboard** and verify that Level is now displayed for each student
- [ ] Click on **Go To Monthly Leaderboard** and verify that Level is hidden for each student

#### Disabled Account
- [ ] In the Web app, disable the account for **QA.MM-DD-YY.student1@suitable.co**
- [ ] Attempt to login into the disabled account on the Mobile app and verify the login is not completed.
